import {
  Apple,
  BarChart3,
  Calculator,
  Dna,
  DollarSign,
  FlaskConical,
  Heart,
  Home,
  MoreHorizontal,
  RefreshCw,
  Trophy,
  Zap,
} from "lucide-react";
import { Tool } from "../types";

export const ALL_TOOLS: Array<Tool> = [
  {
    id: 1,
    name: "Biology",
    icon: Dna,
    description: "Analyze and compare DNA sequences",
    color: "green",
  },
  {
    id: 2,
    name: "Chemistry",
    icon: FlaskConical,
    description: "Calculate molecular weights of compounds",
    color: "blue",
  },
  {
    id: 3,
    name: "Finance",
    icon: DollarSign,
    description: "Calculate loan payments and interest",
    color: "green",
  },
  {
    id: 4,
    name: "Conversions",
    icon: RefreshCw,
    description: "Convert between different units of measurement",
    color: "blue",
  },
  {
    id: 5,
    name: "Statistics",
    icon: BarChart3,
    description: "Perform statistical calculations and analysis",
    color: "green",
  },
  {
    id: 6,
    name: "Food",
    icon: Apple,
    description: "Calculate nutritional values of meals",
    color: "blue",
  },
  {
    id: 7,
    name: "Everyday Life",
    icon: Home,
    description: "Calculate tips and bill splitting",
    color: "green",
  },
  {
    id: 8,
    name: "Health",
    icon: Heart,
    description: "Calculate Body Mass Index and health metrics",
    color: "blue",
  },
  {
    id: 9,
    name: "Maths",
    icon: Calculator,
    description: "Perform matrix operations and calculations",
    color: "green",
  },
  {
    id: 10,
    name: "Physics",
    icon: Zap,
    description: "Calculate forces, energy, and motion",
    color: "blue",
  },
  {
    id: 11,
    name: "Sports",
    icon: Trophy,
    description: "Calculate running pace and race times",
    color: "green",
  },
  {
    id: 12,
    name: "Other",
    icon: MoreHorizontal,
    description: "Generate QR codes from various inputs",
    color: "blue",
  },
];
